CREATE TABLE [dbo].[Module] (
    [Id]                    INT            IDENTITY (1, 1) NOT NULL,
    [FullName]              NVARCHAR (50)  NOT NULL,
    [ScaleId]               INT            NOT NULL,
    [StandardId]            INT            NOT NULL,
    [Theme]                 NVARCHAR (50)  NULL,
    [RepresentsFromYear]    SMALLINT       NULL,
    [RepresentsUptoYear]    SMALLINT       NULL,
    [Radius]                FLOAT (53)     NULL,
    [Angle]                 FLOAT (53)     NULL,
    [Length]                FLOAT (53)     NOT NULL,
    [NumberOfThroughTracks] SMALLINT       CONSTRAINT [DF_Module_ThrougTracksCount] DEFAULT ((1)) NOT NULL,
    [HasNormalGauge]        BIT            NOT NULL,
    [HasNarrowGauge]        BIT            CONSTRAINT [DF_Module_HasNarrowGauge] DEFAULT ((0)) NOT NULL,
    [Is2R]                  BIT            NOT NULL,
    [Is3R]                  BIT            CONSTRAINT [DF_Module_Is3R] DEFAULT ((0)) NOT NULL,
    [IsSignal]              BIT            CONSTRAINT [DF_Module_IsSignal] DEFAULT ((0)) NOT NULL,
    [IsTurntable]           BIT            CONSTRAINT [DF_Module_IsTurntable] DEFAULT ((0)) NOT NULL,
    [IsDuckunder]           BIT            CONSTRAINT [DF_Module_IsDuckunder] DEFAULT ((0)) NOT NULL,
    [IsJunction]            BIT            CONSTRAINT [DF_Module_IsJunction] DEFAULT ((0)) NOT NULL,
    [IsStation]             BIT            CONSTRAINT [DF_Module_IsStation] DEFAULT ((0)) NOT NULL,
    [FunctionalState]       INT            CONSTRAINT [DF_Module_FunctionalState] DEFAULT ((0)) NOT NULL,
    [LandscapeState]        INT            CONSTRAINT [DF_Module_LandscapeState] DEFAULT ((0)) NOT NULL,
    [DwgDrawingId]          INT            NULL,
    [SkpDrawingId]          INT            NULL,
    [PdfDocumentationId]    INT            NULL,
    [Note]                  NVARCHAR (255) NULL,
    [StationId]             INT            NULL,
    [FremoNumber]           INT            NULL,
    [PackageLabel]          NVARCHAR (10)  NULL,
    [ConfigurationLabel]    NVARCHAR (10)  NULL,
    [NumberOfSections]      SMALLINT       NULL,
    [SignalFeature]         INT            CONSTRAINT [DF_Module_SignalOption] DEFAULT ((0)) NOT NULL,
    [OverheadLineFeature]   INT            CONSTRAINT [DF_Module_CatenaryOption] DEFAULT ((0)) NOT NULL,
    [SpeedLimit]            SMALLINT       NULL,
    [ObjectVisibilityId]    INT            CONSTRAINT [DF_Module_ObjectVisibilityId] DEFAULT ((0)) NOT NULL,
    [HasIntegratedLocoNet]  BIT            CONSTRAINT [DF_Module_HasIntegratedLocoNet] DEFAULT ((0)) NOT NULL,
    [IsUnavailable]         BIT            CONSTRAINT [DF_Module_IsUnavailable] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Module] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Module_Document] FOREIGN KEY ([SkpDrawingId]) REFERENCES [dbo].[Document] ([Id]),
    CONSTRAINT [FK_Module_DxfDocument] FOREIGN KEY ([DwgDrawingId]) REFERENCES [dbo].[Document] ([Id]),
    CONSTRAINT [FK_Module_Module] FOREIGN KEY ([Id]) REFERENCES [dbo].[Module] ([Id]),
    CONSTRAINT [FK_Module_ModuleStandard] FOREIGN KEY ([StandardId]) REFERENCES [dbo].[ModuleStandard] ([Id]),
    CONSTRAINT [FK_Module_PdfDocument] FOREIGN KEY ([PdfDocumentationId]) REFERENCES [dbo].[Document] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_Module_Scale] FOREIGN KEY ([ScaleId]) REFERENCES [dbo].[Scale] ([Id]),
    CONSTRAINT [FK_Module_Station] FOREIGN KEY ([StationId]) REFERENCES [dbo].[Station] ([Id]) ON DELETE CASCADE
);

