//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulesRegistry.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModulesRegistry.Services.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon.
        /// </summary>
        internal static string Afternoon {
            get {
                return ResourceManager.GetString("Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists.
        /// </summary>
        internal static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Module Registry.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival.
        /// </summary>
        internal static string Arrival {
            get {
                return ResourceManager.GetString("Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At night.
        /// </summary>
        internal static string At_night {
            get {
                return ResourceManager.GetString("At night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autumn.
        /// </summary>
        internal static string Autumn {
            get {
                return ResourceManager.GetString("Autumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bale.
        /// </summary>
        internal static string Bale {
            get {
                return ResourceManager.GetString("Bale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bales.
        /// </summary>
        internal static string Bales {
            get {
                return ResourceManager.GetString("Bales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrel.
        /// </summary>
        internal static string Barrel {
            get {
                return ResourceManager.GetString("Barrel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrels.
        /// </summary>
        internal static string Barrels {
            get {
                return ResourceManager.GetString("Barrels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best regards.
        /// </summary>
        internal static string BestRegards {
            get {
                return ResourceManager.GetString("BestRegards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bidirectional.
        /// </summary>
        internal static string Bidirectional {
            get {
                return ResourceManager.GetString("Bidirectional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big sack.
        /// </summary>
        internal static string BigSack {
            get {
                return ResourceManager.GetString("BigSack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big sacks.
        /// </summary>
        internal static string BigSacks {
            get {
                return ResourceManager.GetString("BigSacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottle.
        /// </summary>
        internal static string Bottle {
            get {
                return ResourceManager.GetString("Bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottles.
        /// </summary>
        internal static string Bottles {
            get {
                return ResourceManager.GetString("Bottles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        internal static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxes.
        /// </summary>
        internal static string Boxes {
            get {
                return ResourceManager.GetString("Boxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk.
        /// </summary>
        internal static string Bulk {
            get {
                return ResourceManager.GetString("Bulk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle.
        /// </summary>
        internal static string Bundle {
            get {
                return ResourceManager.GetString("Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundles.
        /// </summary>
        internal static string Bundles {
            get {
                return ResourceManager.GetString("Bundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        internal static string Cargo {
            get {
                return ResourceManager.GetString("Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo rack.
        /// </summary>
        internal static string CargoRack {
            get {
                return ResourceManager.GetString("CargoRack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo racks.
        /// </summary>
        internal static string CargoRacks {
            get {
                return ResourceManager.GetString("CargoRacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo unit.
        /// </summary>
        internal static string CargoUnit {
            get {
                return ResourceManager.GetString("CargoUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier.
        /// </summary>
        internal static string Carrier {
            get {
                return ResourceManager.GetString("Carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloned successfully.
        /// </summary>
        internal static string ClonedSuccessfully {
            get {
                return ResourceManager.GetString("ClonedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloning failed.
        /// </summary>
        internal static string CloningFailed {
            get {
                return ResourceManager.GetString("CloningFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        internal static string Community {
            get {
                return ResourceManager.GetString("Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignee.
        /// </summary>
        internal static string Consignee {
            get {
                return ResourceManager.GetString("Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        internal static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create password.
        /// </summary>
        internal static string CreatePassword {
            get {
                return ResourceManager.GetString("CreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic meter.
        /// </summary>
        internal static string Cubicmeter {
            get {
                return ResourceManager.GetString("Cubicmeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic meters.
        /// </summary>
        internal static string Cubicmeters {
            get {
                return ResourceManager.GetString("Cubicmeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string DailyShort {
            get {
                return ResourceManager.GetString("DailyShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPPER.
        /// </summary>
        internal static string DayNameCasing {
            get {
                return ResourceManager.GetString("DayNameCasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully..
        /// </summary>
        internal static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion failed!.
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark.
        /// </summary>
        internal static string Denmark {
            get {
                return ResourceManager.GetString("Denmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        internal static string Departure {
            get {
                return ResourceManager.GetString("Departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain members.
        /// </summary>
        internal static string DomainMembers {
            get {
                return ResourceManager.GetString("DomainMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10&apos; Dry container.
        /// </summary>
        internal static string DryContainer10 {
            get {
                return ResourceManager.GetString("DryContainer10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20&apos; Dry container.
        /// </summary>
        internal static string DryContainer20 {
            get {
                return ResourceManager.GetString("DryContainer20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40&apos; Dry contrainer.
        /// </summary>
        internal static string DryContainer40 {
            get {
                return ResourceManager.GetString("DryContainer40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10&apos; Dry containers.
        /// </summary>
        internal static string DryContainers10 {
            get {
                return ResourceManager.GetString("DryContainers10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20&apos; Dry containers.
        /// </summary>
        internal static string DryContainers20 {
            get {
                return ResourceManager.GetString("DryContainers20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40&apos; Dry contrainers.
        /// </summary>
        internal static string DryContainers40 {
            get {
                return ResourceManager.GetString("DryContainers40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastwards.
        /// </summary>
        internal static string Eastwards {
            get {
                return ResourceManager.GetString("Eastwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East-west.
        /// </summary>
        internal static string EastWest {
            get {
                return ResourceManager.GetString("EastWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epoch.
        /// </summary>
        internal static string Epoch {
            get {
                return ResourceManager.GetString("Epoch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        internal static string Evening {
            get {
                return ResourceManager.GetString("Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export agent.
        /// </summary>
        internal static string ExportAgent {
            get {
                return ResourceManager.GetString("ExportAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault.
        /// </summary>
        internal static string Fault {
            get {
                return ResourceManager.GetString("Fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        internal static string Fixed {
            get {
                return ResourceManager.GetString("Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20&apos; Flat rack container.
        /// </summary>
        internal static string FlatRackContainer20 {
            get {
                return ResourceManager.GetString("FlatRackContainer20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40&apos; Flat rack container.
        /// </summary>
        internal static string FlatRackContainer40 {
            get {
                return ResourceManager.GetString("FlatRackContainer40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20&apos; Flat rack containers.
        /// </summary>
        internal static string FlatRackContainers20 {
            get {
                return ResourceManager.GetString("FlatRackContainers20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40&apos; Flat rack containers.
        /// </summary>
        internal static string FlatRackContainers40 {
            get {
                return ResourceManager.GetString("FlatRackContainers40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fr.
        /// </summary>
        internal static string FridayShort {
            get {
                return ResourceManager.GetString("FridayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully applied, detailed.
        /// </summary>
        internal static string FullyAppliedDetailed {
            get {
                return ResourceManager.GetString("FullyAppliedDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully applied, simple.
        /// </summary>
        internal static string FullyAppliedSimple {
            get {
                return ResourceManager.GetString("FullyAppliedSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        internal static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group members.
        /// </summary>
        internal static string GroupMembers {
            get {
                return ResourceManager.GetString("GroupMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20&apos; High cube container.
        /// </summary>
        internal static string HighCubeContainer20 {
            get {
                return ResourceManager.GetString("HighCubeContainer20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40&apos; High cube container.
        /// </summary>
        internal static string HighCubeContainer40 {
            get {
                return ResourceManager.GetString("HighCubeContainer40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20&apos; High cube containers.
        /// </summary>
        internal static string HighCubeContainers20 {
            get {
                return ResourceManager.GetString("HighCubeContainers20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40&apos; High cube containers.
        /// </summary>
        internal static string HighCubeContainers40 {
            get {
                return ResourceManager.GetString("HighCubeContainers40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40&apos; High cube reefer container.
        /// </summary>
        internal static string HighCubeReeferContainer40 {
            get {
                return ResourceManager.GetString("HighCubeReeferContainer40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40&apos; High cube reefer containers.
        /// </summary>
        internal static string HighCubeReeferContainers40 {
            get {
                return ResourceManager.GetString("HighCubeReeferContainers40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediately.
        /// </summary>
        internal static string Immediately {
            get {
                return ResourceManager.GetString("Immediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import agent.
        /// </summary>
        internal static string ImportAgent {
            get {
                return ResourceManager.GetString("ImportAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the afternoon.
        /// </summary>
        internal static string In_the_afternoon {
            get {
                return ResourceManager.GetString("In the afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the evening.
        /// </summary>
        internal static string In_the_evening {
            get {
                return ResourceManager.GetString("In the evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the morning.
        /// </summary>
        internal static string In_the_morning {
            get {
                return ResourceManager.GetString("In the morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal meeting.
        /// </summary>
        internal static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        internal static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquid container.
        /// </summary>
        internal static string LiquidContainer {
            get {
                return ResourceManager.GetString("LiquidContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquid containers.
        /// </summary>
        internal static string LiquidContainers {
            get {
                return ResourceManager.GetString("LiquidContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading finished.
        /// </summary>
        internal static string LoadingReadyTime {
            get {
                return ResourceManager.GetString("LoadingReadyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May not be deleted..
        /// </summary>
        internal static string MayNotBeDeleted {
            get {
                return ResourceManager.GetString("MayNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mo.
        /// </summary>
        internal static string MondayShort {
            get {
                return ResourceManager.GetString("MondayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning.
        /// </summary>
        internal static string Morning {
            get {
                return ResourceManager.GetString("Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands.
        /// </summary>
        internal static string Netherlands {
            get {
                return ResourceManager.GetString("Netherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No modification.
        /// </summary>
        internal static string NoModification {
            get {
                return ResourceManager.GetString("NoModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-profit association.
        /// </summary>
        internal static string NonProfitAssociation {
            get {
                return ResourceManager.GetString("NonProfitAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noon.
        /// </summary>
        internal static string Noon {
            get {
                return ResourceManager.GetString("Noon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northwards.
        /// </summary>
        internal static string Northwards {
            get {
                return ResourceManager.GetString("Northwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway.
        /// </summary>
        internal static string Norway {
            get {
                return ResourceManager.GetString("Norway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not applicable.
        /// </summary>
        internal static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized.
        /// </summary>
        internal static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to delete..
        /// </summary>
        internal static string NothingToDelete {
            get {
                return ResourceManager.GetString("NothingToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not scheduled.
        /// </summary>
        internal static string NotScheduled {
            get {
                return ResourceManager.GetString("NotScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On demand.
        /// </summary>
        internal static string OnDemand {
            get {
                return ResourceManager.GetString("OnDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On demand.
        /// </summary>
        internal static string OnDemandShort {
            get {
                return ResourceManager.GetString("OnDemandShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only posts.
        /// </summary>
        internal static string OnlyPosts {
            get {
                return ResourceManager.GetString("OnlyPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20&apos; Open top container.
        /// </summary>
        internal static string OpenTopContainer20 {
            get {
                return ResourceManager.GetString("OpenTopContainer20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40&apos; Open top container.
        /// </summary>
        internal static string OpenTopContainer40 {
            get {
                return ResourceManager.GetString("OpenTopContainer40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20&apos; Open top containers.
        /// </summary>
        internal static string OpenTopContainers20 {
            get {
                return ResourceManager.GetString("OpenTopContainers20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40&apos; Open top containers.
        /// </summary>
        internal static string OpenTopContainers40 {
            get {
                return ResourceManager.GetString("OpenTopContainers40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        internal static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        internal static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet.
        /// </summary>
        internal static string Pallet {
            get {
                return ResourceManager.GetString("Pallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallets.
        /// </summary>
        internal static string Pallets {
            get {
                return ResourceManager.GetString("Pallets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially applied.
        /// </summary>
        internal static string PartiallyApplied {
            get {
                return ResourceManager.GetString("PartiallyApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant has registered modules.
        /// </summary>
        internal static string ParticipantHasRegisteredModules {
            get {
                return ResourceManager.GetString("ParticipantHasRegisteredModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not meet policy requirements..
        /// </summary>
        internal static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length {0} characters, consisting of minimum {1} letters {2}, {3} digits {4} and {5} special characters {6}..
        /// </summary>
        internal static string PasswordPolicy {
            get {
                return ResourceManager.GetString("PasswordPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirmed password don&apos;t match..
        /// </summary>
        internal static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces.
        /// </summary>
        internal static string Pieces {
            get {
                return ResourceManager.GetString("Pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        internal static string Planned {
            get {
                return ResourceManager.GetString("Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate.
        /// </summary>
        internal static string Plate {
            get {
                return ResourceManager.GetString("Plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plates.
        /// </summary>
        internal static string Plates {
            get {
                return ResourceManager.GetString("Plates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing.
        /// </summary>
        internal static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to test.
        /// </summary>
        internal static string ReadyToTest {
            get {
                return ResourceManager.GetString("ReadyToTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        internal static string Receive {
            get {
                return ResourceManager.GetString("Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20&apos; Reefer container.
        /// </summary>
        internal static string ReeferContainer20 {
            get {
                return ResourceManager.GetString("ReeferContainer20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40&apos; Reefer container.
        /// </summary>
        internal static string ReeferContainer40 {
            get {
                return ResourceManager.GetString("ReeferContainer40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20&apos; Reefer containers.
        /// </summary>
        internal static string ReeferContainers20 {
            get {
                return ResourceManager.GetString("ReeferContainers20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40&apos; Reefer containers.
        /// </summary>
        internal static string ReeferContainers40 {
            get {
                return ResourceManager.GetString("ReeferContainers40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration closed.
        /// </summary>
        internal static string RegistrationClosed {
            get {
                return ResourceManager.GetString("RegistrationClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration open.
        /// </summary>
        internal static string RegistrationOpen {
            get {
                return ResourceManager.GetString("RegistrationOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removable.
        /// </summary>
        internal static string Removable {
            get {
                return ResourceManager.GetString("Removable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        internal static string Roll {
            get {
                return ResourceManager.GetString("Roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolls.
        /// </summary>
        internal static string Rolls {
            get {
                return ResourceManager.GetString("Rolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sack.
        /// </summary>
        internal static string Sack {
            get {
                return ResourceManager.GetString("Sack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacks.
        /// </summary>
        internal static string Sacks {
            get {
                return ResourceManager.GetString("Sacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sa.
        /// </summary>
        internal static string SaturdayShort {
            get {
                return ResourceManager.GetString("SaturdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved..
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving failed!.
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send {0}..
        /// </summary>
        internal static string SendDays {
            get {
                return ResourceManager.GetString("SendDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper.
        /// </summary>
        internal static string Shipper {
            get {
                return ResourceManager.GetString("Shipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southwards.
        /// </summary>
        internal static string Southwards {
            get {
                return ResourceManager.GetString("Southwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring.
        /// </summary>
        internal static string Spring {
            get {
                return ResourceManager.GetString("Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer.
        /// </summary>
        internal static string Summer {
            get {
                return ResourceManager.GetString("Summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su.
        /// </summary>
        internal static string SundayShort {
            get {
                return ResourceManager.GetString("SundayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden.
        /// </summary>
        internal static string Sweden {
            get {
                return ResourceManager.GetString("Sweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        internal static string Switzerland {
            get {
                return ResourceManager.GetString("Switzerland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tested.
        /// </summary>
        internal static string Tested {
            get {
                return ResourceManager.GetString("Tested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Th.
        /// </summary>
        internal static string ThursdayShort {
            get {
                return ResourceManager.GetString("ThursdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonnes.
        /// </summary>
        internal static string Tonnes {
            get {
                return ResourceManager.GetString("Tonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailers.
        /// </summary>
        internal static string Trailers {
            get {
                return ResourceManager.GetString("Trailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainset.
        /// </summary>
        internal static string Trainset {
            get {
                return ResourceManager.GetString("Trainset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainset with.
        /// </summary>
        internal static string TrainsetWith {
            get {
                return ResourceManager.GetString("TrainsetWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu.
        /// </summary>
        internal static string TuesdayShort {
            get {
                return ResourceManager.GetString("TuesdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under approval.
        /// </summary>
        internal static string UnderApproval {
            get {
                return ResourceManager.GetString("UnderApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under construction.
        /// </summary>
        internal static string UnderConstruction {
            get {
                return ResourceManager.GetString("UnderConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under repair.
        /// </summary>
        internal static string UnderRepair {
            get {
                return ResourceManager.GetString("UnderRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom.
        /// </summary>
        internal static string United_Kingdom {
            get {
                return ResourceManager.GetString("United Kingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload.
        /// </summary>
        internal static string Unload {
            get {
                return ResourceManager.GetString("Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloading finished.
        /// </summary>
        internal static string UnloadingReadyTime {
            get {
                return ResourceManager.GetString("UnloadingReadyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon.
        /// </summary>
        internal static string Wagon {
            get {
                return ResourceManager.GetString("Wagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagons.
        /// </summary>
        internal static string Wagons {
            get {
                return ResourceManager.GetString("Wagons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We.
        /// </summary>
        internal static string WednesdayShort {
            get {
                return ResourceManager.GetString("WednesdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West-east.
        /// </summary>
        internal static string WestEast {
            get {
                return ResourceManager.GetString("WestEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Westwards.
        /// </summary>
        internal static string Westwards {
            get {
                return ResourceManager.GetString("Westwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When needed.
        /// </summary>
        internal static string WhenNeeded {
            get {
                return ResourceManager.GetString("WhenNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When needed.
        /// </summary>
        internal static string WhenNeededShort {
            get {
                return ResourceManager.GetString("WhenNeededShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter.
        /// </summary>
        internal static string Winter {
            get {
                return ResourceManager.GetString("Winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with.
        /// </summary>
        internal static string with {
            get {
                return ResourceManager.GetString("with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years in operation.
        /// </summary>
        internal static string YearsInOperation {
            get {
                return ResourceManager.GetString("YearsInOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
