CREATE TABLE [dbo].[Module] (
    [Id]                    INT            IDENTITY (1, 1) NOT NULL,
    [FullName]              NVARCHAR (50)  NOT NULL,
    [ScaleId]               INT            NOT NULL,
    [StandardId]            INT            NOT NULL,
    [Theme]                 NVARCHAR (50)  NULL,
    [RepresentsFromYear]    SMALLINT       NULL,
    [RepresentsUptoYear]    SMALLINT       NULL,
    [Radius]                FLOAT (53)     NULL,
    [Angle]                 FLOAT (53)     NULL,
    [Straight]              FLOAT (53)     NULL,
    [Length]                FLOAT (53)     NOT NULL,
    [Width]                 FLOAT (53)     NULL,
    [NumberOfThroughTracks] SMALLINT       DEFAULT ((1)) NOT NULL,
    [HasNormalGauge]        BIT            DEFAULT ((1)) NOT NULL,
    [HasNarrowGauge]        BIT            DEFAULT ((0)) NOT NULL,
    [Is2R]                  BIT            DEFAULT ((1)) NOT NULL,
    [Is3R]                  BIT            DEFAULT ((0)) NOT NULL,
    [IsTurntable]           BIT            DEFAULT ((0)) NOT NULL,
    [IsDuckunder]           BIT            DEFAULT ((0)) NOT NULL,
    [IsStandAlone]          BIT            DEFAULT ((1)) NOT NULL,
    [IsEndOfLine]           BIT            DEFAULT ((0)) NOT NULL,
    [IsSignalModule]        BIT            DEFAULT ((0)) NOT NULL,
    [FunctionalState]       INT            DEFAULT ((0)) NOT NULL,
    [LandscapeState]        INT            DEFAULT ((0)) NOT NULL,
    [LandscapeSeason]       INT            DEFAULT ((0)) NOT NULL,
    [DwgDrawingId]          INT            NULL,
    [SkpDrawingId]          INT            NULL,
    [PdfDocumentationId]    INT            NULL,
    [Note]                  NVARCHAR (255) NULL,
    [StationId]             INT            NULL,
    [FremoNumber]           INT            NULL,
    [ConfigurationLabel]    NVARCHAR (10)  NULL,
    [PackageLabel]          NVARCHAR (10)  NULL,
    [CatenaryDescription]   NVARCHAR (50)  NULL,
    [NumberOfSections]      SMALLINT       NULL,
    [SignalFeature]         INT            CONSTRAINT [DF_Module_SignalFeature] DEFAULT ((0)) NOT NULL,
    [OverheadLineFeature]   INT            CONSTRAINT [DF_Module_OverheadLineFeature] DEFAULT ((0)) NOT NULL,
    [SpeedLimit]            SMALLINT       NULL,
    [ObjectVisibilityId]    INT            CONSTRAINT [DF_Module_ObjectVisibilityId] DEFAULT ((0)) NOT NULL,
    [HasIntegratedLocoNet]  BIT            CONSTRAINT [DF_Module_HasIntegratedLoconet] DEFAULT ((0)) NOT NULL,
    [IsUnavailable]         BIT            CONSTRAINT [DF_Module_IsUnavailable] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Module] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Module_Document] FOREIGN KEY ([SkpDrawingId]) REFERENCES [dbo].[Document] ([Id]),
    CONSTRAINT [FK_Module_DxfDocument] FOREIGN KEY ([DwgDrawingId]) REFERENCES [dbo].[Document] ([Id]),
    CONSTRAINT [FK_Module_ModuleStandard] FOREIGN KEY ([StandardId]) REFERENCES [dbo].[ModuleStandard] ([Id]),
    CONSTRAINT [FK_Module_PdfDocument] FOREIGN KEY ([PdfDocumentationId]) REFERENCES [dbo].[Document] ([Id]),
    CONSTRAINT [FK_Module_Scale] FOREIGN KEY ([ScaleId]) REFERENCES [dbo].[Scale] ([Id]),
    CONSTRAINT [FK_Module_Station] FOREIGN KEY ([StationId]) REFERENCES [dbo].[Station] ([Id]) ON DELETE CASCADE
);
GO
CREATE INDEX [IX_Module_StationId] ON [Module] ([StationId]);
GO
