CREATE TABLE [dbo].[Vehicle]
(
    [Id] INT IDENTITY (1, 1) NOT NULL,
    [KeeperCountryId] INT NULL,
    [KeeperSignature] VARCHAR(10) NOT NULL, 
    [VehicleOperatorId] INT NULL,
    [VehicleType] INT NULL,
    [VehicleClass] VARCHAR(10) NOT NULL,
    [VehicleNumber] VARCHAR(20) NOT NULL,
    [VehicleInteroperabilityCode] INT NULL,
    [PrototypeManufacturerName] NVARCHAR(20) NULL,
    [PrototypeManufactureYear] SMALLINT NULL,
    [ThisEmbodiementFromYear] SMALLINT NULL,
    [ThisEmbodiementUptoYear] SMALLINT NULL,
    [TractionFeatureId] INT NULL,
    [EnginePowerUnit] INT DEFAULT (0),
    [EnginePower] SMALLINT NULL,
    [PrototypeLength] DECIMAL (9,3) NULL,
    [PrototypeWeight] DECIMAL (9,3) NULL,
    [PrototypeImageHref] VARCHAR(512) NULL,
    [ScaleId] INT NOT NULL,
    [ModelManufacturerName] NVARCHAR(20) NULL,
    [ModelImage] VARBINARY(MAX) NULL,
    [ModelImageHref] VARCHAR(512) NULL,
    [ModelNumber] NVARCHAR(16) NULL,
    [CouplingFeatureId] INT NULL,
    [WheelsFeatureId] INT NULL,
    [IsWeathered] BIT NOT NULL DEFAULT((0)),
    [Theme] VARCHAR(10) NOT NULL,
    [OwningPersonId] INT NOT NULL,
    [InventoryNumber] INT NOT NULL,
    [DccAddress] SMALLINT NULL,
    [DecoderType] NVARCHAR(20) NULL,
    [HasSound] BIT NOT NULL DEFAULT((0)),
    [HasRemoteCouplings] BIT NOT NULL DEFAULT((0)),
    [F0] NVARCHAR(12) NULL,
    [F1] NVARCHAR(12) NULL,
    [F2] NVARCHAR(12) NULL,
    [F3] NVARCHAR(12) NULL,
    [F4] NVARCHAR(12) NULL,
    [F5] NVARCHAR(12) NULL,
    [F6] NVARCHAR(12) NULL,
    [F7] NVARCHAR(12) NULL,
    [F8] NVARCHAR(12) NULL,
    [F9] NVARCHAR(12) NULL,
    [F10] NVARCHAR(12) NULL,
    [F11] NVARCHAR(12) NULL,
    [F12] NVARCHAR(12) NULL,
    [F13] NVARCHAR(12) NULL,
    [F14] NVARCHAR(12) NULL,
    [F15] NVARCHAR(12) NULL,
    [F16] NVARCHAR(12) NULL,
    [F17] NVARCHAR(12) NULL,
    [F18] NVARCHAR(12) NULL,
    [F19] NVARCHAR(12) NULL,
    [F20] NVARCHAR(12) NULL,
    [F21] NVARCHAR(12) NULL,
    [F22] NVARCHAR(12) NULL,
    [F23] NVARCHAR(12) NULL,
    [F24] NVARCHAR(12) NULL,
    [F25] NVARCHAR(12) NULL,
    [F26] NVARCHAR(12) NULL,
    [F27] NVARCHAR(12) NULL,
    [F28] NVARCHAR(12) NULL,
    [F29] NVARCHAR(12) NULL,
    [Note] NVARCHAR(MAX) NULL, 
    [SellingPrice] DECIMAL(9, 2) NULL, 
    CONSTRAINT [PK_Vehicle] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Vehicle_KeeperCountry] FOREIGN KEY ([KeeperCountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [FK_Vehicle_VehicleOperator] FOREIGN KEY ([VehicleOperatorId]) REFERENCES [dbo].[VehicleOperator] ([Id]),
    CONSTRAINT [FK_Vehicle_VehicleInteroperability] FOREIGN KEY ([VehicleInteroperabilityCode]) REFERENCES [dbo].[VehicleInteroperability] ([Code]),
    CONSTRAINT [FK_Vehicle_Scale] FOREIGN KEY ([ScaleId]) REFERENCES [dbo].[Scale] ([Id]),
    CONSTRAINT [FK_Vehicle_CouplingFeature] FOREIGN KEY ([CouplingFeatureId]) REFERENCES [dbo].[VehicleFeature] ([Id]),
    CONSTRAINT [FK_Vehicle_WheelsFeature] FOREIGN KEY ([WheelsFeatureId]) REFERENCES [dbo].[VehicleFeature] ([Id]),
    CONSTRAINT [FK_Vehicle_OwningPersonId] FOREIGN KEY ([OwningPersonId]) REFERENCES [dbo].[Person] ([Id]),
    CONSTRAINT [UX_Vehicle_InventoryNumber] UNIQUE (OwningPersonId, InventoryNumber)
)
GO

