//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulesRegistry.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModulesRegistry.Data.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autumn.
        /// </summary>
        public static string Autumn {
            get {
                return ResourceManager.GetString("Autumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bidirectional.
        /// </summary>
        public static string Bidirectional {
            get {
                return ResourceManager.GetString("Bidirectional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOWER.
        /// </summary>
        public static string Casing {
            get {
                return ResourceManager.GetString("Casing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club event.
        /// </summary>
        public static string ClubEvent {
            get {
                return ResourceManager.GetString("ClubEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve.
        /// </summary>
        public static string Curve {
            get {
                return ResourceManager.GetString("Curve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain members.
        /// </summary>
        public static string DomainMembers {
            get {
                return ResourceManager.GetString("DomainMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double track.
        /// </summary>
        public static string DoubleTrack {
            get {
                return ResourceManager.GetString("DoubleTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastwards.
        /// </summary>
        public static string Eastwards {
            get {
                return ResourceManager.GetString("Eastwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East-west.
        /// </summary>
        public static string EastWest {
            get {
                return ResourceManager.GetString("EastWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty wagon for {0}.
        /// </summary>
        public static string EmptyWagonForCargo {
            get {
                return ResourceManager.GetString("EmptyWagonForCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        public static string Fixed {
            get {
                return ResourceManager.GetString("Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully applied, detailed.
        /// </summary>
        public static string FullyAppliedDetailed {
            get {
                return ResourceManager.GetString("FullyAppliedDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully applied, simple.
        /// </summary>
        public static string FullyAppliedSimple {
            get {
                return ResourceManager.GetString("FullyAppliedSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group members.
        /// </summary>
        public static string GroupMembers {
            get {
                return ResourceManager.GetString("GroupMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horsepower.
        /// </summary>
        public static string Horsepower {
            get {
                return ResourceManager.GetString("Horsepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete data.
        /// </summary>
        public static string IncompleteData {
            get {
                return ResourceManager.GetString("IncompleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited.
        /// </summary>
        public static string Invited {
            get {
                return ResourceManager.GetString("Invited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junction.
        /// </summary>
        public static string Junction {
            get {
                return ResourceManager.GetString("Junction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilowatt.
        /// </summary>
        public static string Kilowatt {
            get {
                return ResourceManager.GetString("Kilowatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MainTrack {
            get {
                return ResourceManager.GetString("MainTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        public static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module is registered for upcoming meeting.
        /// </summary>
        public static string ModuleIsRegisteredForUpcomingMeeting {
            get {
                return ResourceManager.GetString("ModuleIsRegisteredForUpcomingMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module meeting.
        /// </summary>
        public static string ModuleMeeting {
            get {
                return ResourceManager.GetString("ModuleMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module name/variant is already taken.
        /// </summary>
        public static string ModuleNameIsAlreadyTaken {
            get {
                return ResourceManager.GetString("ModuleNameIsAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not applicable.
        /// </summary>
        public static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorised.
        /// </summary>
        public static string NotAuthorised {
            get {
                return ResourceManager.GetString("NotAuthorised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not 100% owner.
        /// </summary>
        public static string NotFullOwner {
            get {
                return ResourceManager.GetString("NotFullOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to delete.
        /// </summary>
        public static string NothingToDelete {
            get {
                return ResourceManager.GetString("NothingToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not located in track plan.
        /// </summary>
        public static string NotPlacedInLayout {
            get {
                return ResourceManager.GetString("NotPlacedInLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not scheduled.
        /// </summary>
        public static string NotScheduled {
            get {
                return ResourceManager.GetString("NotScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not standalone.
        /// </summary>
        public static string NotStandalone {
            get {
                return ResourceManager.GetString("NotStandalone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only posts.
        /// </summary>
        public static string OnlyPosts {
            get {
                return ResourceManager.GetString("OnlyPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of operation.
        /// </summary>
        public static string OperationsPlace {
            get {
                return ResourceManager.GetString("OperationsPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially applied.
        /// </summary>
        public static string PartiallyApplied {
            get {
                return ResourceManager.GetString("PartiallyApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        public static string Planned {
            get {
                return ResourceManager.GetString("Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preliminary.
        /// </summary>
        public static string Preliminary {
            get {
                return ResourceManager.GetString("Preliminary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing.
        /// </summary>
        public static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to test.
        /// </summary>
        public static string ReadyToTest {
            get {
                return ResourceManager.GetString("ReadyToTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removable.
        /// </summary>
        public static string Removable {
            get {
                return ResourceManager.GetString("Removable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow station.
        /// </summary>
        public static string ShadowStation {
            get {
                return ResourceManager.GetString("ShadowStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siding.
        /// </summary>
        public static string SidingTrack {
            get {
                return ResourceManager.GetString("SidingTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single track.
        /// </summary>
        public static string SingleTrack {
            get {
                return ResourceManager.GetString("SingleTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring.
        /// </summary>
        public static string Spring {
            get {
                return ResourceManager.GetString("Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An operating location must have at least one module referring to it.
        /// </summary>
        public static string StationMustHaveAtLeastOneModuleReferringToIt {
            get {
                return ResourceManager.GetString("StationMustHaveAtLeastOneModuleReferringToIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight.
        /// </summary>
        public static string Straight {
            get {
                return ResourceManager.GetString("Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer.
        /// </summary>
        public static string Summer {
            get {
                return ResourceManager.GetString("Summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tested.
        /// </summary>
        public static string Tested {
            get {
                return ResourceManager.GetString("Tested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks through.
        /// </summary>
        public static string ThroughTracks {
            get {
                return ResourceManager.GetString("ThroughTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        public static string Tracks {
            get {
                return ResourceManager.GetString("Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under approval.
        /// </summary>
        public static string UnderApproval {
            get {
                return ResourceManager.GetString("UnderApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under construction.
        /// </summary>
        public static string UnderConstruction {
            get {
                return ResourceManager.GetString("UnderConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under repair.
        /// </summary>
        public static string UnderRepair {
            get {
                return ResourceManager.GetString("UnderRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West-east.
        /// </summary>
        public static string WestEast {
            get {
                return ResourceManager.GetString("WestEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Westwards.
        /// </summary>
        public static string Westwards {
            get {
                return ResourceManager.GetString("Westwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter.
        /// </summary>
        public static string Winter {
            get {
                return ResourceManager.GetString("Winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
