//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulesRegistry.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModulesRegistry.Data.Resources.Validators", typeof(Validators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all words must begin with capital letter.
        /// </summary>
        public static string AllWordsMustBeginWithCapitalLetter {
            get {
                return ResourceManager.GetString("AllWordsMustBeginWithCapitalLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon classes.
        /// </summary>
        public static string DefaultClasses {
            get {
                return ResourceManager.GetString("DefaultClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a colour.
        /// </summary>
        public static string MustBeAColor {
            get {
                return ResourceManager.GetString("MustBeAColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a DCC-address 1-9999.
        /// </summary>
        public static string MustBeADccAddress {
            get {
                return ResourceManager.GetString("MustBeADccAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a MAC-address.
        /// </summary>
        public static string MustBeAMacAddress {
            get {
                return ResourceManager.GetString("MustBeAMacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be any of {0}.
        /// </summary>
        public static string MustBeAnyOf {
            get {
                return ResourceManager.GetString("MustBeAnyOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be between {0} and {1}.
        /// </summary>
        public static string MustBeBetween {
            get {
                return ResourceManager.GetString("MustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be between {0} and {1} or empty.
        /// </summary>
        public static string MustBeBetweenOrEmpty {
            get {
                return ResourceManager.GetString("MustBeBetweenOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must begin with a capital letter.
        /// </summary>
        public static string MustBeginWithCapitalLetter {
            get {
                return ResourceManager.GetString("MustBeginWithCapitalLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be selected.
        /// </summary>
        public static string MustBeSelected {
            get {
                return ResourceManager.GetString("MustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be a valid DCC-adresses.
        /// </summary>
        public static string MustBeValidDccAdresses {
            get {
                return ResourceManager.GetString("MustBeValidDccAdresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be valid email addresses separated by semicolon.
        /// </summary>
        public static string MustBeValidEmailAddresses {
            get {
                return ResourceManager.GetString("MustBeValidEmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must only contain ordinary text.
        /// </summary>
        public static string MustOnlyContainOrdinaryText {
            get {
                return ResourceManager.GetString("MustOnlyContainOrdinaryText", resourceCulture);
            }
        }
    }
}
